
# Dockerfile to build Samtools container images
# Based on Ubuntu

# Set the base image to Ubuntu
FROM ubuntu:14.04

# File Author / Maintainer
MAINTAINER Alexandra Bomane <bomane@biologie.ens.fr>

# Update the repository sources list
RUN apt-get update

# Install samtools and depending stuff
RUN apt-get install --yes samtools
